import {
    Braces,
    Type,
    Binary,
    Hash,
    Link2,
    Fingerprint,
    FileText,
    KeyRound,
    Pipette,
    ArrowLeftRight,
    Globe,
    Ruler,
    GitBranch,
    QrCode,
    Code2,
    Plug,
    ShieldCheck,
    FileCode,
    Languages,
    Lock,
    Monitor,
    Table2,
    Timer,
    Book,
    Network,
    Wrench,
    Zap,
    Shield,
    Sparkles,
    Heart,
} from 'lucide-react';

export const TOOL_CATEGORIES = [
    {
        title: 'Formatters & Converters',
        icon: Braces,
        tools: [
            {
                href: '/json',
                label: 'JSON Tools',
                description: 'Format, minify, diff, validate, and transform JSON',
                icon: Braces,
                featured: true,
            },
            {
                href: '/text',
                label: 'Text Tools',
                description: 'Convert case, clean text, diff, and analyze',
                icon: Type,
            },
            {
                href: '/base64',
                label: 'Base64 Tools',
                description: 'Encode and decode Base64 for files and media',
                icon: Binary,
            },
            {
                href: '/url-encode',
                label: 'URL Encode / Decode',
                description: 'Encode and decode percent-encoded URLs',
                icon: Link2,
            },
            {
                href: '/html-entity',
                label: 'HTML Entity Encode / Decode',
                description: 'Encode and decode HTML entities',
                icon: FileCode,
            },
            {
                href: '/curl',
                label: 'cURL Converter',
                description: 'Convert cURL to fetch, Axios, Python, and HTTPie',
                icon: Code2,
                featured: true,
            },
            {
                href: '/number-base',
                label: 'Number Base Converter',
                description: 'Binary, octal, decimal, hex, and custom radix',
                icon: Binary,
            },
            {
                href: '/css-unit',
                label: 'CSS Unit Converter',
                description: 'Convert between px, rem, em, vw, vh, pt, cm',
                icon: Ruler,
            },
            {
                href: '/color',
                label: 'Color Picker',
                description: 'Convert HEX, RGB, HSL, OKLCH and generate palettes',
                icon: Pipette,
                featured: true,
            },
            {
                href: '/markdown',
                label: 'Markdown Preview',
                description: 'Write Markdown with live preview',
                icon: FileText,
            },
        ],
    },
    {
        title: 'Generators',
        icon: Hash,
        tools: [
            {
                href: '/id',
                label: 'ID Generator',
                description: 'Generate UUIDs (v1/v4/v7), ULIDs, and NanoIDs',
                icon: Fingerprint,
            },
            {
                href: '/hash',
                label: 'Hash Generator',
                description: 'Generate hashes and HMAC signatures',
                icon: Hash,
            },
            {
                href: '/password-hash',
                label: 'Bcrypt / Argon2 Hasher',
                description: 'Hash and verify passwords with bcrypt and Argon2',
                icon: Lock,
                featured: true,
            },
            {
                href: '/rsa-key',
                label: 'RSA Key Generator',
                description: 'Generate RSA key pairs, format as PEM or DER',
                icon: KeyRound,
            },
            {
                href: '/password',
                label: 'Password Generator',
                description: 'Generate secure passwords with strength meter',
                icon: KeyRound,
            },
            {
                href: '/qrcode',
                label: 'QR Code Generator',
                description: 'Generate customizable QR codes with colors and sizes',
                icon: QrCode,
            },
            {
                href: '/git-branch-generator',
                label: 'Git Branch Generator',
                description: 'Generate consistent git branch names from templates',
                icon: GitBranch,
            },
        ],
    },
    {
        title: 'Network & API',
        icon: Network,
        tools: [
            {
                href: '/api-builder',
                label: 'API Request Builder',
                description: 'Build, test, and debug HTTP requests online',
                icon: Globe,
                featured: true,
            },
            {
                href: '/websocket',
                label: 'WebSocket Tester',
                description: 'Connect to WS endpoints, send and receive messages',
                icon: Plug,
            },
            {
                href: '/cors',
                label: 'CORS Checker',
                description: 'Test cross-origin requests and inspect CORS headers',
                icon: ShieldCheck,
            },
            {
                href: '/cert-decoder',
                label: 'Certificate Decoder',
                description: 'Decode and inspect SSL/TLS certificate fields',
                icon: Fingerprint,
            },
            {
                href: '/user-agent',
                label: 'User Agent Analyzer',
                description: 'Parse and decode User-Agent strings',
                icon: Monitor,
            },
            {
                href: '/nslookup',
                label: 'DNS Lookup',
                description: 'Query NS, A, AAAA, MX, TXT, CNAME, SOA, PTR records',
                icon: Globe,
            },
        ],
    },
    {
        title: 'Reference',
        icon: Book,
        tools: [
            {
                href: '/regex',
                label: 'Regex Tester',
                description: 'Test regex with live matching and capture groups',
                icon: FileText,
                featured: true,
            },
            {
                href: '/http-status',
                label: 'HTTP Status Codes',
                description: 'Searchable reference with descriptions and specs',
                icon: Globe,
            },
            {
                href: '/mime-type',
                label: 'MIME Type Reference',
                description: 'File extension ↔ MIME type mapping',
                icon: FileText,
            },
            {
                href: '/unicode',
                label: 'Unicode Lookup',
                description: 'Search Unicode characters by name and codepoint',
                icon: Languages,
            },
            {
                href: '/ascii-table',
                label: 'ASCII Table',
                description: 'Interactive ASCII reference table with search and copy',
                icon: Table2,
            },
        ],
    },
    {
        title: 'Utilities',
        icon: Wrench,
        tools: [
            {
                href: '/cron',
                label: 'CRON Builder',
                description: 'Visual cron expression builder with next-run preview',
                icon: Timer,
                featured: true,
            },
            {
                href: '/unit',
                label: 'Unit Converter',
                description: 'Data sizes, time durations, and time zones',
                icon: ArrowLeftRight,
            },
            {
                href: '/url-shortener',
                label: 'URL Shortener',
                description: 'Shorten long URLs into compact shareable links',
                icon: Link2,
            },
        ],
    },
];

export const FEATURES = [
    {
        icon: Zap,
        title: 'Lightning Fast',
        description: 'All tools run locally in your browser. No server uploads, no waiting.',
    },
    {
        icon: Shield,
        title: 'Privacy First',
        description: 'Your data never leaves your browser. 100% client-side processing.',
    },
    {
        icon: Sparkles,
        title: 'Modern Design',
        description: 'Clean, intuitive interface with dark mode support and responsive layout.',
    },
    {
        icon: Heart,
        title: 'Free Forever',
        description: 'All tools are completely free with no sign-up required.',
    },
];
