import {
    Book,
    FileJson,
    FileText,
    FileCode,
    GitBranch,
    Link2,
    QrCode,
    Hash,
    Link,
    Fingerprint,
    Regex,
    KeyRound,
    Pipette,
    Binary,
    ArrowLeftRight,
    Globe,
    Ruler,
    Monitor,
    Zap,
    Code2,
    Plug,
    ShieldCheck,
    Braces,
    Network,
    Wrench,
    Languages,
    Lock,
    Table2,
    Timer,
} from 'lucide-react';

export interface MenuItem {
    title: string;
    url: string;
    description?: string;
    icon?: React.ReactNode;
    category?: string;
    items?: MenuItem[];
}

export const navigationMenu: MenuItem[] = [
    {
        title: 'Tools',
        url: '#',
        items: [
            {
                title: 'JSON Tools',
                description: 'Format, diff, validate — stop wrestling with broken JSON',
                icon: <FileJson className="size-5 shrink-0" />,
                url: '/json',
                category: 'Formatters & Converters',
            },
            {
                title: 'Text Tools',
                description: 'Diff, convert case, and clean messy text in seconds',
                icon: <FileText className="size-5 shrink-0" />,
                url: '/text',
                category: 'Formatters & Converters',
            },
            {
                title: 'Base64 Tools',
                description: 'Encode files or decode Base64 — drag and drop',
                icon: <FileCode className="size-5 shrink-0" />,
                url: '/base64',
                category: 'Formatters & Converters',
            },
            {
                title: 'URL Encode / Decode',
                description: 'Fix mangled URLs with one click',
                icon: <Link className="size-5 shrink-0" />,
                url: '/url-encode',
                category: 'Formatters & Converters',
            },
            {
                title: 'HTML Entity Encode / Decode',
                description: 'Make special characters HTML-safe instantly',
                icon: <FileCode className="size-5 shrink-0" />,
                url: '/html-entity',
                category: 'Formatters & Converters',
            },
            {
                title: 'cURL Converter',
                description: 'Paste cURL, get fetch/Axios/Python code',
                icon: <Code2 className="size-5 shrink-0" />,
                url: '/curl',
                category: 'Formatters & Converters',
            },
            {
                title: 'Number Base Converter',
                description: 'Binary to hex and everything between — all bases at once',
                icon: <Binary className="size-5 shrink-0" />,
                url: '/number-base',
                category: 'Formatters & Converters',
            },
            {
                title: 'CSS Unit Converter',
                description: 'px to rem and back — with your real viewport size',
                icon: <Ruler className="size-5 shrink-0" />,
                url: '/css-unit',
                category: 'Formatters & Converters',
            },
            {
                title: 'Color Picker',
                description: 'Pick colors and build harmonious palettes',
                icon: <Pipette className="size-5 shrink-0" />,
                url: '/color',
                category: 'Formatters & Converters',
            },
            {
                title: 'Markdown Preview',
                description: 'Write Markdown, see the result live',
                icon: <FileText className="size-5 shrink-0" />,
                url: '/markdown',
                category: 'Formatters & Converters',
            },
            {
                title: 'ID Generator',
                description: 'UUIDs and ULIDs for every version you need',
                icon: <Fingerprint className="size-5 shrink-0" />,
                url: '/id',
                category: 'Generators',
            },
            {
                title: 'Hash Generator',
                description: 'MD5, SHA-256, SHA-512 — all hashes at once',
                icon: <Hash className="size-5 shrink-0" />,
                url: '/hash',
                category: 'Generators',
            },
            {
                title: 'Bcrypt / Argon2 Hasher',
                description: 'Hash passwords with production-grade algorithms',
                icon: <Lock className="size-5 shrink-0" />,
                url: '/password-hash',
                category: 'Generators',
            },
            {
                title: 'RSA Key Generator',
                description: 'Generate RSA keys without remembering OpenSSL commands',
                icon: <KeyRound className="size-5 shrink-0" />,
                url: '/rsa-key',
                category: 'Generators',
            },
            {
                title: 'Password Generator',
                description: 'Strong passwords with entropy scoring built in',
                icon: <KeyRound className="size-5 shrink-0" />,
                url: '/password',
                category: 'Generators',
            },
            {
                title: 'QR Code Generator',
                description: 'Custom QR codes with your colors and size',
                icon: <QrCode className="size-5 shrink-0" />,
                url: '/qrcode',
                category: 'Generators',
            },
            {
                title: 'Git Branch Generator',
                description: 'Consistent branch names without the naming debates',
                icon: <GitBranch className="size-5 shrink-0" />,
                url: '/git-branch-generator',
                category: 'Generators',
            },
            {
                title: 'API Request Builder',
                description: 'Test APIs without installing Postman',
                icon: <Zap className="size-5 shrink-0" />,
                url: '/api-builder',
                category: 'Network & API',
            },
            {
                title: 'WebSocket Tester',
                description: 'Debug WebSocket connections in real-time',
                icon: <Plug className="size-5 shrink-0" />,
                url: '/websocket',
                category: 'Network & API',
            },
            {
                title: 'CORS Checker',
                description: 'Fix CORS errors — see exactly which headers are missing',
                icon: <ShieldCheck className="size-5 shrink-0" />,
                url: '/cors',
                category: 'Network & API',
            },
            {
                title: 'Certificate Decoder',
                description: 'Decode SSL certs without OpenSSL',
                icon: <Fingerprint className="size-5 shrink-0" />,
                url: '/cert-decoder',
                category: 'Network & API',
            },
            {
                title: 'User Agent Analyzer',
                description: 'Decode any User-Agent string instantly',
                icon: <Monitor className="size-5 shrink-0" />,
                url: '/user-agent',
                category: 'Network & API',
            },
            {
                title: 'DNS Lookup',
                description: 'Check DNS records without opening a terminal',
                icon: <Globe className="size-5 shrink-0" />,
                url: '/nslookup',
                category: 'Network & API',
            },
            {
                title: 'Regex Tester',
                description: 'Test regex live — see matches as you type',
                icon: <Regex className="size-5 shrink-0" />,
                url: '/regex',
                category: 'Reference',
            },
            {
                title: 'HTTP Status Codes',
                description: 'Every status code explained in plain English',
                icon: <Globe className="size-5 shrink-0" />,
                url: '/http-status',
                category: 'Reference',
            },
            {
                title: 'MIME Type Reference',
                description: 'Stop Googling MIME types — look them up here',
                icon: <FileText className="size-5 shrink-0" />,
                url: '/mime-type',
                category: 'Reference',
            },
            {
                title: 'Unicode Lookup',
                description: 'Find any character and copy in every format',
                icon: <Languages className="size-5 shrink-0" />,
                url: '/unicode',
                category: 'Reference',
            },
            {
                title: 'ASCII Table',
                description: 'Searchable ASCII reference with one-click copy',
                icon: <Table2 className="size-5 shrink-0" />,
                url: '/ascii-table',
                category: 'Reference',
            },
            {
                title: 'CRON Builder',
                description: 'Build cron expressions without memorizing syntax',
                icon: <Timer className="size-5 shrink-0" />,
                url: '/cron',
                category: 'Utilities',
            },
            {
                title: 'Unit Converter',
                description: 'Data sizes, time durations, and timezones',
                icon: <ArrowLeftRight className="size-5 shrink-0" />,
                url: '/unit',
                category: 'Utilities',
            },
            {
                title: 'URL Shortener',
                description: 'Turn long links into short, shareable ones',
                icon: <Link2 className="size-5 shrink-0" />,
                url: '/url-shortener',
                category: 'Utilities',
            },
        ],
    },
    {
        title: 'Share Text',
        url: '/share/text',
    },
    {
        title: 'Resources',
        url: '#',
        items: [
            {
                title: 'Documentation',
                description: 'Master every tool in under 2 minutes',
                icon: <Book className="size-5 shrink-0" />,
                url: '/docs',
            },
        ],
    },
];

export const authButtons = {
    login: { title: 'Login', url: '/login' },
    signup: { title: 'Sign up', url: '/signup' },
};

export const CATEGORY_ICONS: Record<string, React.ReactNode> = {
    'Formatters & Converters': <Braces className="size-3.5" />,
    Generators: <Hash className="size-3.5" />,
    'Network & API': <Network className="size-3.5" />,
    Reference: <Book className="size-3.5" />,
    Utilities: <Wrench className="size-3.5" />,
};
